import contextlib
import io
import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch
import sys

import setup as installer
sys.path.insert(0, str(Path(__file__).parent.parent / 'omarchy-plugin'))
import keybindings


class SetupTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        root = Path(self.temp.name)
        self.root = root
        self.env = patch.dict(os.environ, {'HOME': str(root), 'XDG_CONFIG_HOME': str(root/'config'),
                                          'XDG_DATA_HOME': str(root/'data'), 'XDG_STATE_HOME': str(root/'state')})
        self.env.start(); self.addCleanup(self.env.stop)
        self.loc = installer.paths()
        self.commands = []
        def run(*args, **kwargs):
            self.commands.append(tuple(str(a) for a in args))
            if args[:2] == ('uv', 'venv'):
                target = Path(args[-1]) / 'bin/python'
                target.parent.mkdir(parents=True)
                target.write_text('fixture environment')
            if args[:3] == ('systemctl', '--user', 'is-active'): return 'inactive'
            return ''
        for item in (patch.object(installer, 'run', side_effect=run), patch.object(installer, 'check_dependencies'),
                     patch.object(installer, 'ensure_idle'), patch.object(keybindings, 'read', return_value={'primary':'','alternative':''}),
                     patch.object(keybindings, 'apply')):
            item.start(); self.addCleanup(item.stop)

    def install(self):
        with contextlib.redirect_stdout(io.StringIO()): installer.install()

    def test_fresh_install_update_and_uninstall_preserve_user_data(self):
        self.install()
        self.assertTrue(self.loc['launcher'].exists())
        self.assertIn(str(self.loc['runtime']), self.loc['unit'].read_text())
        self.assertNotIn('Projects/', self.loc['unit'].read_text())
        manifest = json.loads((self.loc['plugin']/'manifest.json').read_text())
        self.assertEqual(manifest['entryPoints']['service'], 'omarchy-plugin/Service.qml')
        history = self.loc['state']/'my-dictation.txt'; history.write_text('keep me')
        model = self.loc['data']/'models/custom.onnx'; model.parent.mkdir(); model.write_text('keep me')
        unrelated = self.loc['config']/'systemd/user/other.service'; unrelated.write_text('keep me')
        self.install()
        with contextlib.redirect_stdout(io.StringIO()): installer.uninstall()
        self.assertFalse(self.loc['launcher'].exists())
        self.assertFalse(self.loc['unit'].exists())
        self.assertTrue(all(p.exists() for p in (history, model, unrelated)))
        self.assertFalse(self.loc['ledger'].exists())
        self.assertFalse(self.loc['plugin'].exists())
        self.install()
        self.assertTrue((self.loc['plugin']/'manifest.json').is_file())

    def test_uninstall_removes_derived_bytecode_but_preserves_unrelated_files(self):
        self.install()
        cache = self.loc['plugin']/'__pycache__/model_store.cpython-314.pyc'
        cache.parent.mkdir(); cache.write_bytes(b'generated bytecode')
        unrelated = self.loc['plugin']/'user-notes.txt'; unrelated.write_text('keep')
        with contextlib.redirect_stdout(io.StringIO()): installer.uninstall()
        self.assertFalse(cache.exists())
        self.assertEqual(unrelated.read_text(), 'keep')

    def test_install_refuses_foreign_launcher(self):
        self.loc['launcher'].parent.mkdir(parents=True)
        self.loc['launcher'].write_text('foreign executable')
        with self.assertRaisesRegex(RuntimeError, 'Unmanaged'):
            self.install()
        self.assertEqual(self.loc['launcher'].read_text(), 'foreign executable')

    def test_update_failure_rolls_back_installed_files(self):
        self.install()
        before = self.loc['unit'].read_bytes()
        original_run = installer.run.side_effect
        def run(*args, **kwargs):
            if args[:4] == ('systemctl','--user','enable','--now'):
                raise RuntimeError('simulated service failure')
            return original_run(*args, **kwargs)
        with patch.object(installer, 'run', side_effect=run), patch.object(installer, 'unit_text', return_value='new unit'):
            with self.assertRaisesRegex(RuntimeError, 'simulated'):
                self.install()
        self.assertEqual(self.loc['unit'].read_bytes(), before)

    def test_modified_files_are_preserved_on_uninstall(self):
        self.install()
        self.loc['launcher'].write_text('user edited')
        with contextlib.redirect_stdout(io.StringIO()): installer.uninstall()
        self.assertEqual(self.loc['launcher'].read_text(), 'user edited')
        self.assertTrue(self.loc['ledger'].exists())

    def test_update_reconciles_identical_managed_plugin_file(self):
        self.install()
        target = self.loc['plugin'] / 'omarchy-plugin/Settings.qml'
        ledger = json.loads(self.loc['ledger'].read_text())
        ledger['files'][str(target)]['installed_sha256'] = 'previous deployment'
        self.loc['ledger'].write_text(json.dumps(ledger))
        self.install()
        ledger = json.loads(self.loc['ledger'].read_text())
        self.assertEqual(ledger['files'][str(target)]['installed_sha256'], installer.digest(target))

    def test_update_refuses_modified_launcher(self):
        self.install()
        self.loc['launcher'].write_text('user change')
        with self.assertRaisesRegex(RuntimeError, 'modified'):
            self.install()
        self.assertEqual(self.loc['launcher'].read_text(), 'user change')

    def test_enable_failure_restores_previous_unit_and_plugin_placement(self):
        self.install()
        config = self.loc['config']/'omarchy/shell.json'
        config.parent.mkdir(parents=True, exist_ok=True)
        config.write_text(json.dumps({'bar': {'layout': {'left': [{'id': installer.PLUGIN_ID}, {'id': 'omarchy.clock'}]}}}))
        before = self.loc['unit'].read_bytes()
        original_run = installer.run.side_effect
        failed = []
        def run(*args, **kwargs):
            if args[:3] == ('omarchy','plugin','enable') and not failed:
                failed.append(True)
                raise RuntimeError('activation failed')
            return original_run(*args, **kwargs)
        with patch.object(installer, 'run', side_effect=run), patch.object(installer, 'unit_text', return_value='new unit'):
            with self.assertRaisesRegex(RuntimeError, 'activation failed'):
                self.install()
        self.assertEqual(self.loc['unit'].read_bytes(), before)
        self.assertIn(('omarchy','plugin','enable',installer.PLUGIN_ID,'--section','left','--before','omarchy.clock'), self.commands)

    def test_release_excludes_private_files_environments_and_symlinks(self):
        export = installer.export(self.root/'release')
        self.assertTrue((export/'manifest.json').exists())
        self.assertTrue((export/'LICENSE').exists())
        self.assertTrue((export/'omarchy-plugin/Status.js').exists())
        for module in ('Ui', 'Commons'):
            self.assertTrue((export/'tests/qml/qs'/module/'qmldir').is_file())
        self.assertFalse(any(p.is_symlink() for p in export.rglob('*')))
        self.assertFalse(any(p.name in ('.venv','backup','__pycache__','VALIDATION.md') for p in export.rglob('*')))
        self.assertFalse(any(p.suffix in ('.wav','.log') for p in export.rglob('*')))


if __name__ == '__main__': unittest.main()
